name: Deployment Homolog

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: steebchen/flutter@v1.1.0
        with:
          args: pub get

      - name: Build AppBundle
        uses: steebchen/flutter@v1.1.0
        with:
          args: build appbundle --release --no-sound-null-safety

