name: Deployment Homolog

on:
  # workflow_dispatch:
  - push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AppBundle
        run: flutter build appbundle --release --no-sound-null-safety

