name: Deployment Homolog

on:
  workflow_dispatch:
  #- push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Checkout Google Json
        run: |
          versionFile='android/app/google-services.json'
          gist_url='https://gist.githubusercontent.com/brunoalvesdasilva/'
          gist_id='68991eac6ef645a353139aadb04a64f2'
          gist_rawfile='/raw'
          gist_raw_endpoint=$gist_url$gist_id$gist_rawfile
          curl -s "${gist_raw_endpoint}" -o "${versionFile}"

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build AppBundle
        run: flutter build appbundle --release --no-sound-null-safety

      - name: Install gem
        run: |
          sudo gem install bundler
          bundle config set path vendor/bundle
          bundle check || bundle install

      - name: Checkversion fastlane
        run: |
          bundle exec fastlane deploy

